Formatting + update for Monterey
dortania/Wireless-Buyers-Guide pull request #30
Opened 2021-11-09 20:38 UTC by alyxxxx

I think I edited every single markdown file in this repository. Was in need of some polishing. Updated info for Monterey as well.

2021-11-10 05:02 UTC, 1Revenger1 requested changes

2021-11-10 05:02 UTC, 1Revenger1 commented on types-of-wireless-card/m2.md
> +  * BrcmBluetoothInjector (don't use on macOS 12)
ditto above comment about min/max kernel

2021-11-10 16:35 UTC, alyxxxx commented on Kext.md
> +* BrcmBluetoothInjector (don't use on macOS 12)
Resolved with d9dc2b2 and 4348eec

2021-11-10 16:36 UTC, alyxxxx commented on Kext.md
> +* OpenCore order: Injector -> Data -> RAM
Resolved with 55d2ee5

2021-11-10 16:38 UTC, alyxxxx commented on README.md
> +So you've finally installed macOS onto your desktop/laptop/smart fridge, but you look towards the menubar and see a Bluetooth icon yet no wifi to go with. You immediately bolt to the Settings pane an
Resolved with 3b64130
Didn't know ANON is usually capitalized, thought it was to show intonation 😆

2021-11-10 16:46 UTC, alyxxxx commented on types-of-wireless-card/m2.md
> +  * BrcmBluetoothInjector (don't use on macOS 12)
Resolved with a42a721

2021-11-10 19:03 UTC, alyxxxx commented
I think it should be good to go at this point unless you'd like something else done

2022-02-06 07:48 UTC, 1Revenger1 approved these changes

2022-02-06 07:48 UTC, merged